"""initial migration

Revision ID: 001_initial_migration
Revises: 
Create Date: 2025-05-10 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001_initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Créer les types d'énumération
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'commander', 'field')")
    op.execute("CREATE TYPE clearancelevel AS ENUM ('top_secret', 'secret', 'confidential')")
    
    # Table users
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('matricule', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('admin', 'commander', 'field', name='userrole'), nullable=False),
        sa.Column('clearance_level', sa.Enum('top_secret', 'secret', 'confidential', name='clearancelevel'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_matricule'), 'user', ['matricule'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_matricule'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    
    # Supprimer les types d'énumération
    op.execute("DROP TYPE userrole")
    op.execute("DROP TYPE clearancelevel")
    # ### end Alembic commands ###